name: Autopep8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download and install Python 3.13
      run: |
        sudo apt update -y; sudo  apt upgrade -y; sudo apt install software-properties-common -y; sudo add-apt-repository ppa:deadsnakes/ppa -y ; sudo apt update -y ; sudo apt install python3.13 -y
        sudo apt install python3-distutils -y
        sudo apt install python3.13-venv -y
        python3.13 -m ensurepip --upgrade
        python3.13 -m pip install --upgrade pip

    - name: Install required packages
      run: |
        python3.13 -m pip install autopep8

    - name: Run autopep8
      run: |
        python3.13 -m autopep8 --in-place --recursive hw2
