name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autopep8-check:
    name: autopep8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install autopep8
      run: |
        python -m pip install --upgrade pip
        python -m pip install autopep8

    - name: Run autopep8
      run: |
        autopep8 --in-place --recursive hw2

  pylint-check:
    name: Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint

    - name: Run pylint
      run: |
        pylint hw2

  bandit-check:
    name: Bandit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install bandit
      run: |
        python -m pip install --upgrade pip
        python -m pip install bandit

    - name: Run bandit
      run: |
        bandit -r hw2

  pytest-check:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest

    - name: Run pytest
      run: |
        pytest test.py
