name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autopep8-check:
    name: autopep8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget build-essential libssl-dev libffi-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev libncurses5-dev \
        libncursesw5-dev xz-utils tk-dev

    - name: Download and install Python 3.13
      run: |
        wget https://www.python.org/ftp/python/3.13.0a1/Python-3.13.0a1.tgz
        tar -xf Python-3.13.0a1.tgz
        cd Python-3.13.0a1
        ./configure --enable-optimizations
        make -j$(nproc)
        sudo make altinstall

    - name: Install required packages
      run: |
        /usr/local/bin/python3.13 -m pip install --upgrade pip
        /usr/local/bin/python3.13 -m pip install autopep8 pylint bandit pytest

    - name: Run autopep8
      run: |
        /usr/local/bin/python3.13 -m autopep8 --in-place --recursive hw2

  pylint-check:
    name: Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget build-essential libssl-dev libffi-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev libncurses5-dev \
        libncursesw5-dev xz-utils tk-dev

    - name: Download and install Python 3.13
      run: |
        wget https://www.python.org/ftp/python/3.13.0a1/Python-3.13.0a1.tgz
        tar -xf Python-3.13.0a1.tgz
        cd Python-3.13.0a1
        ./configure --enable-optimizations
        make -j$(nproc)
        sudo make altinstall

    - name: Install required packages
      run: |
        /usr/local/bin/python3.13 -m pip install --upgrade pip
        /usr/local/bin/python3.13 -m pip install pylint

    - name: Run pylint
      run: |
        /usr/local/bin/python3.13 -m pylint hw2

  bandit-check:
    name: Bandit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget build-essential libssl-dev libffi-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev libncurses5-dev \
        libncursesw5-dev xz-utils tk-dev

    - name: Download and install Python 3.13
      run: |
        wget https://www.python.org/ftp/python/3.13.0a1/Python-3.13.0a1.tgz
        tar -xf Python-3.13.0a1.tgz
        cd Python-3.13.0a1
        ./configure --enable-optimizations
        make -j$(nproc)
        sudo make altinstall

    - name: Install required packages
      run: |
        /usr/local/bin/python3.13 -m pip install --upgrade pip
        /usr/local/bin/python3.13 -m pip install bandit

    - name: Run bandit
      run: |
        /usr/local/bin/python3.13 -m bandit -r hw2

  pytest-check:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget build-essential libssl-dev libffi-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev libncurses5-dev \
        libncursesw5-dev xz-utils tk-dev

    - name: Download and install Python 3.13
      run: |
        wget https://www.python.org/ftp/python/3.13.0a1/Python-3.13.0a1.tgz
        tar -xf Python-3.13.0a1.tgz
        cd Python-3.13.0a1
        ./configure --enable-optimizations
        make -j$(nproc)
        sudo make altinstall

    - name: Install required packages
      run: |
        /usr/local/bin/python3.13 -m pip install --upgrade pip
        /usr/local/bin/python3.13 -m pip install pytest

    - name: Run pytest
      run: |
        /usr/local/bin/python3.13 -m pytest test.py