name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-python:
    name: Set up Python 3.12 (or desired version)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download and install Python 3.12
      run: |
        wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
        tar -xf Python-3.12.0.tgz
        cd Python-3.12.0
        ./configure --enable-optimizations
        make -j$(nproc)
        sudo make altinstall

    - name: Verify Python version
      run: |
        python3.12 --version
        pip3.12 --version

    - name: Add Python 3.12 to PATH
      run: |
        # Add Python 3.12 executable and pip to PATH
        echo "::set-path name=PATH::$HOME/.local/bin"

  autopep8-check:
    name: autopep8
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run autopep8
      run: |
        /usr/local/bin/python3.13 -m autopep8 --in-place --recursive hw2

  pylint-check:
    name: Pylint
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run pylint
      run: |
        /usr/local/bin/python3.13 -m pylint hw2

  bandit-check:
    name: Bandit
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run bandit
      run: |
        /usr/local/bin/python3.13 -m bandit -r hw2

  pytest-check:
    name: Pytest
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run pytest
      run: |
        /usr/local/bin/python3.13 -m pytest test.py