name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autopep8-check:
    name: autopep8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget build-essential libssl-dev libffi-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev libncurses5-dev \
        libncursesw5-dev xz-utils tk-dev
        wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0a1.tgz
        tar -xf Python-3.13.0a1.tgz
        cd Python-3.13.0a1
        sudo make altinstall
        python3.13 --version
        python3.13 -m pip install --upgrade pip autopep8

    - name: Run autopep8
      run: |
        autopep8 --in-place --recursive hw2

  pylint-check:
    name: Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget build-essential libssl-dev libffi-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev libncurses5-dev \
        libncursesw5-dev xz-utils tk-dev
        wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0a1.tgz
        tar -xf Python-3.13.0a1.tgz
        cd Python-3.13.0a1
        sudo make altinstall
        python3.13 --version
        python3.13 -m pip install pylint

    - name: Run pylint
      run: |
        pylint hw2

  bandit-check:
    name: Bandit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget build-essential libssl-dev libffi-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev libncurses5-dev \
        libncursesw5-dev xz-utils tk-dev
        wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0a1.tgz
        tar -xf Python-3.13.0a1.tgz
        cd Python-3.13.0a1
        sudo make altinstall
        python3.13 --version
        python3.13 -m pip install bandit

    - name: Run bandit
      run: |
        bandit -r hw2

  pytest-check:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget build-essential libssl-dev libffi-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev libncurses5-dev \
        libncursesw5-dev xz-utils tk-dev
        wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0a1.tgz
        tar -xf Python-3.13.0a1.tgz
        cd Python-3.13.0a1
        sudo make altinstall
        python3.13 --version
        python3.13 -m pip install pytest

    - name: Run pytest
      run: |
        pytest test.py