name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-python:
    name: Set up Python 3.13
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget build-essential libssl-dev libffi-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev libncurses5-dev \
        libncursesw5-dev xz-utils tk-dev

    - name: Install Python 3.13
      run: |
        wget https://github.com/python/cpython/releases/download/v3.13.0a1/Python-3.13.0a1-linux-x86_64.tar.xz
        tar -xf Python-3.13.0a1-linux-x86_64.tar.xz
        sudo mkdir -p /usr/local/python3.13
        sudo cp -r Python-3.13.0a1/* /usr/local/python3.13/
        sudo ln -s /usr/local/python3.13/bin/python3.13 /usr/local/bin/python3
        sudo ln -s /usr/local/python3.13/bin/pip3.13 /usr/local/bin/pip3

    - name: Verify Python version
      run: |
        /usr/local/bin/python3 --version
        /usr/local/bin/pip3 --version

    - name: Install required packages
      run: |
        /usr/local/bin/python3 -m pip install --upgrade pip
        /usr/local/bin/python3 -m pip install autopep8 pylint bandit pytest

  autopep8-check:
    name: autopep8
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run autopep8
      run: |
        /usr/local/bin/python3 -m autopep8 --in-place --recursive hw2

  pylint-check:
    name: Pylint
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run pylint
      run: |
        /usr/local/bin/python3 -m pylint hw2

  bandit-check:
    name: Bandit
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run bandit
      run: |
        /usr/local/bin/python3 -m bandit -r hw2

  pytest-check:
    name: Pytest
    runs-on: ubuntu-latest
    needs: setup-python

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run pytest
      run: |
        /usr/local/bin/python3 -m pytest test.py