name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies for building Python
      run: |
        sudo apt update
        sudo apt install -y wget build-essential libssl-dev libffi-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev libncurses5-dev libncursesw5-dev xz-utils tk-dev

    - name: Download and install Python 3.13
      run: |
        wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0a1.tgz
        tar -xf Python-3.13.0a1.tgz
        cd Python-3.13.0a1
        ./configure --enable-optimizations
        make -j$(nproc)
        sudo make altinstall
        python3.13 --version

    - name: Upgrade pip
      run: |
        python3.13 -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        python3.13 -m pip install autopep8 pyflakes pylint bandit pytest

    - name: Run autopep8
      run: |
        autopep8 --in-place --recursive hw2

    - name: Run pylint
      run: |
        pylint hw2

    - name: Run bandit
      run: |
        bandit -r hw2

    - name: Run pytest
      run: |
        pytest test.py